### ISSUE TITLE
OTP web takes you to the credentials tab when accesing with Ubuntu

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode_OTP#25]
When you access from an Ubuntu machine, you land in the credentials tab not in the linux tab

**Comment by jubalharsho** [comment]
Hi! DAppNode seems interesting project and I am happy to help. I know it's not much but I fixed this issue in PR #27 and tested it locally. Hope you like it.

**Comment by dapplion** [comment]
Thank you @jubalharsho for your contribution

**Comment by jubalharsho** [comment]
Thank you too!
