### ISSUE TITLE
Executing the echo script to get the VPN credentials for Ubuntu returns a file in only one line

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode_OTP#29]
Even though this might be solved with the ubuntu config file issue, when you cat the file returned by the scripts it is only in one line, just to let you know...

https://user-images.githubusercontent.com/21328788/46866093-419ec680-ce20-11e8-9637-e4ab8fa6c75d.png

**Comment by dapplion** [comment]
@Shelpin Is this issue still persisting? Thank you!

**Comment by Shelpin** [comment]
Closing because moving to OpenVPN
