### ISSUE TITLE
Broken OTP Link when scanning the QR shown in the console

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode_OTP#38]
The QR shown after the installation of the ADMIN version 18 and dappmanager version 22 with:

```sudo wget -O - https://github.com/dappnode/DAppNode/releases/download/v0.1.18/dappnode_install.sh | sudo ADMIN_VERSION=0.1.18 DAPPMANAGER_VERSION=0.1.22 bash```

 directs to a Broken OTP link web page when scanning the QR with the mobile. If you copy the link as shown in text in te console it works fine. 

![image](https://user-images.githubusercontent.com/21328788/54355876-88f0e380-465a-11e9-9208-a0a03e44dc00.png)

This is the URL where the link takes you to

https://dappnode.github.io/DAppNode_OTP/

and this how the notification of the detected link appears 

![image](https://user-images.githubusercontent.com/21328788/54356023-dbca9b00-465a-11e9-9992-71007a19d16f.png)

**Comment by dapplion** [comment]
Already fixed in 0.1.x and not relevant anymore for 0.2.0.
Lesson learned:
- Keep the protocol `http://` in the url or iPhone will freak out and not understand the QR
